### ISSUE TITLE
TypeError: 'MarkovChain' object is not iterable

### ISSUE THREAD

**Issue by agustindiaz90** [QuantEcon/QuantEcon.applications#41]
I am trying to run the codes to replicate the Arellano model in python but I can't resolve the following issue. My code is: 

```
import numpy as np
import matplotlib.pyplot as pet
import quantecon as qe
from arellano_vfi import Arellano_Economy

ae = Arellano_Economy(beta=.953,        # time discount rate
                        gamma=2.,       # risk aversion
                        r=0.017,        # international interest rate
                        rho=.945,       # persistence in output 
                        eta=0.025,      # st dev of output shock
                        theta=0.282,    # prob of regaining access 
                        ny=21,          # number of points in y grid
                        nB=251,         # number of points in B grid
                        tol=1e-8,       # error tolerance in iteration
                        maxit=10000)
```

and I get the following error:

```
>>> import numpy as np
>>> import matplotlib.pyplot as pet
import quantecon as qe
>>> from arellano_vfi import Arellano_Economy

ae = Arellano_Economy(beta=.953,        # time discount rate
                        gamma=2.,       # risk aversion
                        r=0.017,        # international interest rate
                        rho=.945,       # persistence in output 
>>> >>> >>> ... ... ... ...                         eta=0.025,      # st dev of output shock
...                         theta=0.282,    # prob of regaining access 
...                         ny=21,          # number of points in y grid
...                         nB=251,         # number of points in B grid
...                         tol=1e-8,       # error tolerance in iteration
...                         maxit=10000)
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "arellano_vfi.py", line 74, in __init__
    log_ygrid, Py = qe.markov.tauchen(rho, eta, 3, ny)
TypeError: 'MarkovChain' object is not utterable

```

Someone know how to fix it?

**Comment by oyamad** [comment]
Hi @agustindiaz90
A quick workaround is to replace [line 74](https://github.com/QuantEcon/QuantEcon.applications/blob/master/arellano/arellano_vfi.py#L74) in `arellano_vfi.py` with

```py
mc = qe.markov.tauchen(rho, eta, 3, ny)
log_ygrid, Py = mc.state_values, mc.P
```

I hope it works.

(The issue is that the change in the return values of `tauchen` made by QuantEcon.py/#250 has not been incorporated in arellano_vfi.py`.)

**Comment by agustindiaz90** [comment]
Thanks @oyamad, it works great!!

**Comment by oyamad** [comment]
@agustindiaz90 You are welcome.

@cc7768 @jstac Would you update the code in `arellano_vfi.py`? Perhaps `mc` should be stored as `self.mc` once instantiated, to be called in `simulate`.

**Comment by jstac** [comment]
@agustindiaz90 Many thanks for reporting this bug.  It's much appreciated.  Sorry for the slow response.  I've fixed `arellano_vfi.py` and the solution notebook is running correctly.

See, e.g., [here](https://github.com/QuantEcon/QuantEcon.applications/blob/master/arellano/arellano_vfi.py#L74).  (The code visible on the lecture site itself might not update for a few more days.)

cc @oyamad @cc7768
